### ISSUE TITLE
Support proxying connections

### ISSUE THREAD

**Issue by Cubxity** [NukkitX/Protocol#152]
Add support for proxying connections via a proxy, such as [SOCKS5](https://en.wikipedia.org/wiki/SOCKS#SOCKS5). This is useful for networking behind a firewall or other application-specific usecases.

**Comment by SupremeMortal** [comment]
Version 3.0 supports modifying the entire netty pipeline, so it is possible to integrate a custom solution to support SOCKS5 however, there is no plan for it to be directly supported by this library.
