### ISSUE TITLE
please support for 1.19.21

### ISSUE THREAD

**Issue by CoolLoong** [NukkitX/Protocol#169]

**Comment by Camotoy** [comment]
For now you can do this as a "workaround":

```java
public static final BedrockPacketCodec DEFAULT_BEDROCK_CODEC = Bedrock_v544.V544_CODEC.toBuilder()
            .minecraftVersion("1.19.21")
            .protocolVersion(545)
            .build();
```

**Comment by CoolLoong** [comment]
> For now you can do this as a "workaround":
> 
> ```java
> public static final BedrockPacketCodec DEFAULT_BEDROCK_CODEC = Bedrock_v544.V544_CODEC.toBuilder()
>             .minecraftVersion("1.19.21")
>             .protocolVersion(545)
>             .build();
> ```

Thanks, but why not merge PR#168
