### ISSUE TITLE
Add FLAG_FORCE_MOVE_LOCAL_ENTITY to MoveEntityAbsolutePacket

### ISSUE THREAD

**Issue by BrandPVP** [NukkitX/Protocol#201]
Please, add FLAG_FORCE_MOVE_LOCAL_ENTITY  to the MoveEntityAbsolutePacket
Here
https://github.com/CloudburstMC/Protocol/blob/e56c90e45c66685a5ad2e66aca181e702330e80f/bedrock-codec/src/main/java/org/cloudburstmc/protocol/bedrock/packet/MoveEntityAbsolutePacket.java#L17

From pocketmine
https://github.com/pmmp/BedrockProtocol/blob/99c1bb4a9139e17aef4c5ebd1459dcf482e6ea88/src/MoveActorAbsolutePacket.php#L25

**Comment by Alemiz112** [comment]
Should be fixed in https://github.com/CloudburstMC/Protocol/commit/c690dedc9dda3bf191643e47823d8fdf8138f98a.
