### ISSUE TITLE
How to enable Experiments? 

### ISSUE THREAD

**Issue by MadeAja** [NukkitX/Protocol#206]
Experiment Short Sneak

**Comment by IndianBartonka** [comment]
Not possible now, wait , today (07.06.2023) Minecraft 1.20 is out
(This is client side i guess)

**Comment by Kazzuk** [comment]
Experiments can be enabled/disabled in the `StartGamePacket` [here](https://github.com/CloudburstMC/Protocol/blob/4edf086d10290260027389ca0441e01e12c39efe/bedrock-codec/src/main/java/org/cloudburstmc/protocol/bedrock/packet/StartGamePacket.java#L57).
