### ISSUE TITLE
Move Player Bug

### ISSUE THREAD

**Issue by Valaphee** [NukkitX/Protocol#27]
Greetings,

my problem is not really related to this project, but I have no plan to fix it, because everything seems right.
I'm trying to move players with the appropriate "MovePlayerPacket" but, I the Bedrock Client just replies with the last coordinates, and on the client-side my player ist just rotating. The entity absolute move packet works just for the current player.

I send everything that Nukkit also sends. Hopefully anyone has an idea which causes that strange behavior of the client. It's no problem to reverse engineer the server but the client...

Kind regards
Valaphee

P.S.: Here are some of the packets logged:
https://tmp.valaphee.com/bagabilewu.js
BE = Bedrock Edition

**Comment by lukeeey** [comment]
Discord: https://discord.gg/5PzMkyK
