### ISSUE TITLE
MethodNotFound SerializedSkin.getArmSize()

### ISSUE THREAD

**Issue by james090500** [NukkitX/Protocol#33]
Seems there's not getArmSize() in SerializedSkin in the latest 2.5.5-SNAPSHOT

https://paste.gg/p/anonymous/94088ceea32141cbb97dd2824f734915

**Comment by SupremeMortal** [comment]
If you're running maven, I suggest force updating your dependencies with `mvn -U`
It's likely that the bedrock-common is out of sync with the `bedrock-v390` module

**Comment by james090500** [comment]
That sorted it out. Thanks
