### ISSUE TITLE
No Longer Compatible With PS4 Bedrock Edition

### ISSUE THREAD

**Issue by hiimcody1** [NukkitX/Protocol#37]
After testing various projects using this framework, it appears that PS4's Bedrock Edition doesn't work properly any longer.

When using two editions of Bedrock (Win10 and PS4) I am able to complete the handshake and connect using the Win10 edition, however the PS4 edition consistently fails.

When the PS4 is trying to connect, the "Locating server" dialog completely freezes for a few seconds, as if it is processing something, but then it unfreezes and begins to just spin there until I cancel it.

I'm testing with various implementations of the Protocol framework ranging from Nukkit itself (various branches), Geyser, and even DragonProxy.

The closest I've been able to get to connecting is using the "master" branch of Nukkit, however it simply crashes the PS4 version.

To confirm I didn't have a network issue at play, I also tried the official Bedrock server software and confirmed that the PS4 can connect to it without issues.

**Comment by SupremeMortal** [comment]
I just logged in fine with Nukkit 2.0 (which uses this protocol library) on a PS4.

**Comment by hiimcody1** [comment]
It looks like it may be my PS4 then. Just tried using another one on the same network and MS account, and that one works fine.

I apologize for wasting anyone's time on this.
