### ISSUE TITLE
When will bedrock-v407 codec be published to NukkitX Maven repo?

### ISSUE THREAD

**Issue by JustDerb** [NukkitX/Protocol#48]
I see there is a feature branch for the 1.16 update, with protocol v407 committed. I also see the Jenkins builds are "passing": https://ci.nukkitx.com/job/NukkitX/job/Protocol/job/feature%252F1.16/

Is there any more testing needed before these change can be published to the NukkitX Maven repo?

**Comment by popkechupki** [comment]
I heard there is a problem about block palettes.

**Comment by bundabrg** [comment]
Probably just manually compile it first for your own dev or if you're desperate I have it in my maven repo for now.
```
        <!-- Bundabrg's Repo -->
        <repository>
            <id>bundabrg-repo</id>
            <url>https://repo.worldguard.com.au/repository/maven-public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
```

**Comment by SupremeMortal** [comment]
It has been deployed to the snapshot repo the past couple of days.
